theme: jekyll-theme-leap-day
title: Lazy Results
description: Lazy versions of Result objects
current_version: 0.6.2.0
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
exclude:
  - gradle
  - result-lazy
